### ISSUE TITLE
Identity 3.x on .Net Standard Framework

### ISSUE THREAD

**Issue by john2014** [aspnet/Identity#1147]
I am currently using membership and would like to migrate to Identity. Here are few questions I had:

1. Are there any plans to port Identity 3.x to .Net Standard 4.6.x? Currently .Net Standard 4.6.x only supports Identity upto 2.2.1 (which was last updated two years ago).
2. Is it possible for Identity 2.x, 3.x to work with Postgresql DB (instead of MS SQL server only)? Is there a easy migration process from Membership (SQL Server only) to Identity 2.x/3.x (Postgresql Server).
3. Is is possible to use Identity without using Entity Framework?
4. Last question: I am currently using Membership and would like to implement something similar to Identity 3.x on Postgresql DB on .Net Standard 4.6.x (without Entity Framework). Is it possible for you to direct me to GitHub source code which gives us the following: (a) How to create FormsAuthentication Cookie (b) How to salt and hash password during registration or login process (c) How to check if User.Identity.IsAuthenticated (d) How to get User.Identity.Name?

I apologized for asking these basic questions - but since there are so many files spread across many GitHub projects (Identity, Core, OWIN, Entity Framework, OAuth, Security,  etc), I am not sure where to start looking on how to do question 4 above.

Thank you so much for your help 😄

**Comment by blowdart** [comment]
1) There is no .NET Standard 4.6.x. I guess you mean Framework, and not standard, and you mean MVC5? If so, no. Core Identity is linked to ASP.NET Core, which is turn is linked to .NET Core. We won't be bringing it down to MVC5, or earlier.
2) The EF abstraction should enable you to use any database EF supports. Someone [wrote a provider ](https://blog.samikuhmonen.fi/post/2016/04/30/asp-net-core-identity-and-postgresql) for Identity Core (Which I think you mean when you say 3.x ). We don't provide one out of the box. There's no migration, because, well, we don't provide postgresql support.
3) You can write your own provider.
4) Identity does all that, so the source code would be identity :)

**Comment by john2014** [comment]
Thanks Barry. I was hoping to use Identity 3.x with .Net Framework 4.6 on Postgresql (without Entity Framework and without MVC). It looks like this use case would not be supported. 

BTW, since Identity and other new features in .Net Core are not been back ported to .Net Framework, does this means that Microsoft is officially (or unofficially) planning to start deprecating .Net Framework?

**Comment by blowdart** [comment]
It's certainly not deprecated, but it's unlikely it'll see more major releases of identity on it, just bug fixes.
