### ISSUE TITLE
SignInManager ->GetExternalLoginInfoAsync

### ISSUE THREAD

**Issue by jkljajic** [aspnet/Identity#1151]
in SignInManager in Method GetExternalLoginInfoAsync at line 579
var providerKey = auth.Principal.FindFirstValue(ClaimTypes.NameIdentifier);

this is fixed claimTypes and all fails if we change ClaimsIdentity.UserNameClaimType
maybe is better to replace it with 
var providerKey = auth.Principal.FindFirstValue(options.ClaimsIdentity.UserNameClaimType);

i am not shore if this is bug or intended like this.

**Comment by blowdart** [comment]
This UserNameClaimType is the claim we create in your sign in cookie, and is what you get from Identity.Name.

NameIdentifer is what the auth pieces use to indicate what the auth provider says their username is. So, if you signed in with google, this would be your google user name. 

So they're entirely separate, changing the UserNameClaimType doesn't affect NameIdentitfier.

It's by design.
