### ISSUE TITLE
*Manager classes lack cancellation support

### ISSUE THREAD

**Issue by MovGP0** [aspnet/Identity#1335]
The `I*Store` interfaces (`IUserPasswordStore<TUser>`, `IUserEmailStore<TUser>`, `IUserClaimStore<TUser>`, `IRoleClaimStore<TRole>`, etc.) provide cancellation support by supporting a `CancellationToken`, ie. in case the connection to the database time out. 

However, this is not exposed by the `Manager` classes, so a canceled HTTP request cannot cancel the database access.

**Comment by HaoK** [comment]
Identity uses the RequestAborted cancellationToken from HttpContext by default, you can replace it with a different one by setting the property in 2.0 with a custom manager https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L52

**Comment by mdekrey** [comment]
Given the line linked, it looks like it uses `CancellationToken.None` my default; it doesn't look like the code has changed since @HaoK's comment, either. 

I'm curious on the design decision here as opposed to having default parameters of `CancellationToken cancellationToken = default(CancellationToken)` that I see in most other areas of the framework. Can someone enlighten me? Thanks in advance!

I also imagine that it's more common to have multiple CancellationToken sources than to provide a custom manager, and it feels heavy-handed to do so.
