### ISSUE TITLE
Unable to add duplicate usernames with different company IDs

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/Identity#1518]
**Use case**: I'm using a multi-tenancy for my asp.net core app however, different tenants/companies are stored on the same schema and the same database. Since each tenant/company is different from each other and have no access to each other, the app should allow registering users that are unique within a company. In otherwords, it should allow saving users to the database with the same username but have different tenant/company id.
**Issue**: ASP.NET Core 2 is creating a UniqueUsername index that does not allow me to add a user with the same username. Is there another way to override this index in Code-First approach? Something like transforming this UniqueUsername index to UniqueUsername+company id, wherein the user is unique per username per company.

**Comment by blowdart** [comment]
@ajcvickers This looks like an EF question really, so here you go :)

**Comment by whizkidwwe1217** [comment]
@blowdart I don't think this is an issue with EF core or a question but an issue with Identity

Issue: A unique constraint is hard-coded to the IdentityUserContext. This means that it does not allow me to implement a multi-tenant users. The current architecture is only good for multi-tenant apps where each tenant database is being hosted to different servers. But in the case of multi-tenancy where companies/tenants share a single database, it's not possible to do with the current version of Asp.net core Identity library.

![image](https://user-images.githubusercontent.com/1977391/33768112-aa87f080-dc5f-11e7-9dd0-733dc9b35471.png)
Expectation: 
I should be able to make the user (IdentityUser) unique per username (NormalizeName) per CompanyId (another field). This should be also the same with identity Roles.

**Comment by blowdart** [comment]
True, Identity was never designed for, nor meant for multi-tenancy. We've had people do it, via various unsupported means, and you can override that OnModelBuilding to try a composite key, but, again, you're heading down the unsupported route. I tagged Arthur in case it had details on how you'd change the model to do what you want.

**Comment by whizkidwwe1217** [comment]
Thanks @blowdart I actually tried to override the OnModelBuilding but it's giving me errors like the image below:
![image](https://user-images.githubusercontent.com/1977391/33769551-9ace4c88-dc65-11e7-9ad1-b45bde69b10b.png)

Anyway, I already filed a similar issue in EF core repo and I hope 
@ajcvickers can help me with this. Thanks! :) 
https://github.com/aspnet/EntityFrameworkCore/issues/10511

**Comment by ajcvickers** [comment]
@whizkidwwe1217 It might be possible to change that index and retain an EF model that still works correctly, but this will be more than a simple change in OnModelCreating and would require an intimate knowledge of how Identity is currently using the model. I don't have enough knowledge to do that, and based on my understanding from others there is little chance of getting it to work correctly since Identity was not designed to support this.

**Comment by HaoK** [comment]
Something you can try is to use a convention like {tenantId}-{userName} as the user name for identity

**Comment by whizkidwwe1217** [comment]
I actually managed to make it work by creating a custom user validator and I didn't use IdentityDbContext. Instead, I derived a new db context from DbContext class and copied all dbsets and configurations from identity context. Kind of a hack actually but it works.

**Comment by weedkiller** [comment]
This should be groups or tenants so that the users are nested under different companies
Identity is missing this..

so many people are requesting groups and tenants
 https://github.com/aspnet/Identity/issues?utf8=%E2%9C%93&q=is%3Aissue+group , https://github.com/aspnet/Identity/issues/1532 , 
https://github.com/aspnet/Identity/issues/545 , 
https://github.com/aspnet/Identity/issues/184 , 
https://github.com/aspnet/Identity/issues/586 ,
https://github.com/aspnet/Identity/issues/184 ,
https://github.com/aspnet/Identity/issues/83 ,
https://github.com/aspnet/Identity/issues/62 ,
https://github.com/aspnet/Identity/issues/1187 ,
https://github.com/aspnet/Identity/issues/1518

**Comment by whizkidwwe1217** [comment]
@challamzinniagroup it's just so bad when you're putting in some random strings when it doesn't have to be. I'll already solved this issue by extending and overriding the IdentityManager class. That way I was able to customize it and was able decide how it will be persisted to the database.
