### ISSUE TITLE
Improve the extensibility of the default identity UI

### ISSUE THREAD

**Issue by javiercn** [aspnet/Identity#1572]
Support changing the user type from IdentityUser to TUser while using the default UI.

**Comment by PinpointTownes** [comment]
Why is it limited to entities that inherit from `IdentityUser`? Why can't we use the default UI with totally custom entities?

/cc @HaoK

**Comment by HaoK** [comment]
The decision was made for 2.0 templates to start using the properties on IdentityUser directly instead going thru the user manager for things like user.Id for some of the exception messages.  That binds the views to IdentityUser.  I did bring this up at the time the change was made so it was intentional, You can ask @DamianEdwards / @danroth27 to consider revisit that decision

**Comment by DamianEdwards** [comment]
Now that the UI in is hidden away in a library, I'd be OK with revisiting that. We'd need to consider what to do with the scaffolder content though.

**Comment by PinpointTownes** [comment]
Okay, I opened a new ticket to track that: https://github.com/aspnet/Identity/issues/1679.
