### ISSUE TITLE
FindByIdAsync uses string instead of TKey

### ISSUE THREAD

**Issue by wiktor-golonka** [aspnet/Identity#1589]
Method FindByIdAsync still uses string as a type of id instead of using type from TKey.

I am implementing my custom UserStore like that:
```
public class ApplicationUserStore : UserStore<ApplicationUser,Role,ApplicationDbContext,int,ApplicationUserClaim,ApplicationUserRole,ApplicationUserLogin,ApplicationUserToken,ApplicationRoleClaim>
{

}
```

All of the models above are using int as a key.

**Comment by HaoK** [comment]
This is by design, the interface is always a string, stores are free to persist the keys using whatever type they want, but they are responsible for converting it to/from a string.

The base stores have virtual ConvertIdTo/FromString methods to make this easier:
https://github.com/aspnet/Identity/blob/dev/src/Stores/UserStoreBase.cs#L239
