### ISSUE TITLE
Identity-UI MVC scaffolder

### ISSUE THREAD

**Issue by iAmBipinPaul** [aspnet/Identity#1658]
scaffolding UI in the from of MVC pattern, so that it will be easy to manage for application that is built using MVC template instead of Razor Page template.

**Comment by Eilon** [comment]
@javiercn ?

**Comment by javiercn** [comment]
Is there any reason/scenario that prevents you from just using the Razor pages version? Razor pages are designed to seamlessly inter-operate with traditional MVC controllers/views. Is there any place where you are running into issues?

We are not planning at this time to provide an MVC version of the scaffolder at this time unless we get significant feedback about it. Maintaining two parallel versions of the code base incurs in a significant cost for us with little/no benefit.

If you have specific issue with the Razor pages version that might require an MVC version of the Identity UI code, we would like to hear about it.

**Comment by javiercn** [comment]
@DamianEdwards

**Comment by iambipinpaul** [comment]
@javiercn 
No there isn't any reason/scenario as  of now  that prevents me from using Razor page version with MVC. It's just my personal preference to have everything in one stack. 

> In a future release we plan to update the identity scaffolder to support scaffolding only specific pages and provide a UI for selecting which pages you want, but for now the identity scaffolder is all or nothing and you have to remove the pages you don't want.

I'm thinking in this way later it can have some flags to generate Razor Page/MVC/ or JUST Controller and Models (API).

**Comment by javiercn** [comment]
I'll let @DamianEdwards chime in

**Comment by Ponant** [comment]
Attribute routing is lacking in Pages (at least a few month ago), would that be a good reason?

**Comment by Alienroid** [comment]
I can think of an use case. I am pretty new with Razor Pages, so please correct me if I am wrong. My thought is that Razor Pages is for HTML and MVC is good for all sorts of calls. If that's the case, then there's a use case of using identity not for HTML. 

Few projects I worked on have only mobile applications as client that uses identity. In this case, since it's not HTML, doesn't make sense to use Razor Pages. I'd need to scaffold for Razor Pages, copy the code to a MVC file, then delete the scaffolded Razor Pages.

**Comment by DamianEdwards** [comment]
We don't have any plans to invest in a version of the scaffolders that emit controllers & views at this time. Maintaining two copies of the functionality in two different patterns is obviously a cost and right now it seems the only benefit to being to use controllers & views is one of "preference" rather than a concrete lack of capability.
