### ISSUE TITLE
Compiled Razor views won't override default UI

### ISSUE THREAD

**Issue by jenyayel** [aspnet/Identity#1673]
I wonder if it is by design. 

I'm trying out [Identity UI as a library](https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/). 

It works fine unless I want to add some customization. Instead of scaffolding, I'm using `AddDefaultUI()` and then handpicking which views to override within my app. If I override, for instance, by adding a new file in my app `Areas/Identity/Pages/Account/Register.cshtml`, it will work fine when running/debugging locally. 

However, I noticed that when the app published, the override won't work - it will display views that comes from `AddDefaultUI()`. I made sure that the `<Something>.PrecompiledViews.dll` is generated and contains my app's views. If I opt out to precompiled views by adding `<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>` in `csproj` the overrides starts working.

**Comment by DamianEdwards** [comment]
@javiercn @Eilon @mkArtakMSFT

**Comment by javiercn** [comment]
@pranavkm Is looking into this.

**Comment by pranavkm** [comment]
@jenyayel this was likely a bug in the order of compiled views discovered from the library and the ones from the app. In preview1, the semantics were along the lines of Runtime Compiled Views -> Views from the Identity Library (it had an attribute that made it special) -> all views from .PrecompiledViews.dll. That explains the behavior you're seeing. Using the switch to disable precompilation in the app would be a good way to workaround this.

For preview2, we've moved to a different model of compiling Razor views so that the application produces a compiled view assembly both at build and publish time. This should generally eliminate these kinds of discrepancies between build and publish time. I'll do a quick sanity check to verify this issue is resolved in preview2 and get back to you.

**Comment by pranavkm** [comment]
Ok, verified this is no longer an issue with preview2 bits. (Microsoft.AspNetCore.App: `2.1.0-preview2-30500`). I dropped in a file and was able to verify it is overriden both during build and publish times.
