### ISSUE TITLE
Moving IdentityUser and other POCOs to core seems to lock this more to EF, excluding other databases

### ISSUE THREAD

**Issue by ngbrown** [aspnet/Identity#332]
I noticed that the path on Identity 3 has been to move the POCO classes to core (see #35).  This is resulting in a very Entity Framework focused implementation.

For example, a document databases would not include parent id's in the sub-entities.  NHibernate strongly prefers use objects for references and not stand-alone reference id's, this is making it harder to implement.

Also with using GuidComb or identity IDs, NHibernate pretty much requires that the assignment take place at database save/flush, so there is no writing of the ID to the sub-entities (`IdentityUserLogin`, `IdentityUserClaim`, `IdentityUserRole`).  Instead the parent object is stored as a property.

I would recommend providing interfaces in the core with all the properties desired, but leave the final concrete class (like referencing the parent with PersonId) to the per-database implementations.

**Comment by divega** [comment]
@ngbrown This is something that we have discussed a bit about within the team but the arguments for moving the types hadn't been strong enough, so your feedback is very much appreciated!

There are a couple of caveats: 

1. The fact that the entities are in the "core" Identity assembly does not mean you have use them. They are there just as an optional starting point for the actual entities which are defined in the application. Any storage provider implementation can skip them. 

2. The entities we currently have aren't really typical EF entities. In an actual application model designed to work with EF you should expect to see object references (navigation properties) used often as a representation of the associations in the model. The absence of navigation properties is an indirect consequence the access pattern we use in the EF storage implementation of Identity: We defer loading of related data until the data is needed by our APIs, and when load the related data we do so exclusively through the explicit execution of queries. Since we are not using either eager loading nor lazy loading, between two calls to Identity APIs the navigation properties would most often be null, and any application code attempting to consume the object graph would need to account for that. After a discussion we settled on removing the navigation properties to get rid of that potential source of surprise/problems, and we agreed that when customers actually want to have navigation properties in the Identity entities, e.g. because they have integrated the Identity classes into their application domain, they can include the navigation properties (this decision is of course also open for feedback).

**Comment by HaoK** [comment]
Yeah basically the idea behind moving these to core was to make it easier to reuse our default POCOs if desired.  There are no real dependencies in core on these pocos, so stores are free to ignore them and do what they like, with no limitations.

**Comment by ngbrown** [comment]
Thanks for the response.  I think with all the requests and commands really supposed to be going through `RoleManager` and `UserManager`, it really doesn't make much sense having these entities publicly available in the core, especially if they are not going to be used.

It makes it too easy for the developer to try to use the entities directly instead of going through the managers like they are supposed to.  Then they run into problems when a specific port doesn't even use them in their implementation of the manager.

**Comment by rustd** [comment]
- Bing back navigation properties in POCO and configure them. Let them do the default behavior
- Move POCO to EF assembly

**Comment by suhasj** [comment]
Added navigation properties back into the POCO and moved it to EF namespace
https://github.com/aspnet/Identity/pull/378
