### ISSUE TITLE
Error Applying Identity Migration Column 'AspNetRoles.Id' is not the same length or scale as referencing column... 

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#340]
When adding Microsoft.AspNet.Identity to our nearly empty MVC EF7 project, we receive the following error when we perform the "k ef migration add initial" to a blank database.
  
Error Encountered:
Column 'AspNetRoles.Id' is not the same length or scale as referencing column 'AspNetRoleClaims.RoleId' in foreign key 'FK_AspNetRoleClaims_AspNetRoles_RoleId'. Columns participating in a foreign key relationship must be defined with the same length and scale.
Could not create constraint. See previous errors.  
   
Dependencies used:
"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta1",
"Microsoft.AspNet.Security.Cookies": "1.0.0-beta1",
"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta1",
"Microsoft.Framework.Logging": "1.0.0-beta1"

We can't see how we might be causing this error with our code but we have seen it work in the StarterWeb sample project with the exact same dependencies and versions.  We thought to float this up to wiser minds.  We have taken a look at the generated migration code and did not see where string length for 'AspNetRoles.Id', 'AspNetRoleClaims.RoleId' or 'FK_AspNetRoleClaims_AspNetRoles_RoleId' is explicitly specified.

**Comment by heathyates** [comment]
We have created a basic application that demonstrates this error. See repo here: https://github.com/HeathWillCode/SampleIdentity

Steps to reproduce: 

1. Navigate to application directory
2. k ef migration add init

It will then display the error message we described above.

**Comment by WillBaldwin** [comment]
Here is my theory....  
On the StarterWeb project template in VS2015 it includes a migration file "000000000000000_CreateIdentitySchema.cs".  ASPNET.Identity does not yet support creation of a migration file.  In order to get the identity schema built for a new project people will have to obtain the file "000000000000000_CreateIdentitySchema.cs" from the StarterWeb project template in VS2015 and copy it in to your new project Migrations folder. Edit this file and fix the namespace and the references to the DBContext class.  Then run "K ef migration add Identity".

**Comment by suhasj** [comment]
does this repro with beta2 packages ?

**Comment by suhasj** [comment]
I verified that the repro works fine with the latest beta3 packages from https://www.myget.org/F/aspnetrelease/ feed. Reopen if you still see an issue

**Comment by heathyates** [comment]
@suhasj I am unable to update this repo to beta2. The EntityFramework.Commands doesn't work. That is, "k ef". I then read above that you got it working for you, with beta3. @suhasj , I believe you. So what could be going on for me? 

Frankly, I am having a ton of problem with the packages and dependencies. Can you please take a peek at [this](https://github.com/aspnet/MusicStore/issues/374) and let me know what is going on? I know other folks are experiencing this issue, but no "solution" has been found. I think all my problems are related to not being able to bring in the latest packages/dependencies and all kinds of issues that I encounter because of it.

**Comment by heathyates** [comment]
@suhasj Can you please explain why you used https://www.myget.org/F/aspnetrelease and not https://www.myget.org/F/aspnetvnext/api/v2? What nugget source should I be using for my demo?

**Comment by heathyates** [comment]
@suhasj I cannot reopen this issue. I believe this is because I didn't create it. However, I updated the repo and I have the following steps to show you my current problem: 

Startup.cs
![startup](https://cloud.githubusercontent.com/assets/1896424/6063664/9377dba8-ad1e-11e4-98df-bb029b386093.PNG)

Dependencies in project.json
![dependencies](https://cloud.githubusercontent.com/assets/1896424/6063669/99d029a6-ad1e-11e4-9e8d-c86a886cc749.PNG)

NuGet 
![aspnetrelease](https://cloud.githubusercontent.com/assets/1896424/6063730/14377a3c-ad1f-11e4-905c-58e3303ceabd.PNG)

Guess: Is this because my KRE (beta2) is not matching the packages version beta3? If so, how can I update my KRE from beta2 to beta3? I would really appreciate an explanation as to what could have gone wrong. Thanks.

**Comment by suhasj** [comment]
Yes the issue might be because you are using beta2 KRE with beta3 packages. To install KRE outside VS, you need to do it using `kvm`. Visit the https://github.com/aspnet/Home/ which has instructions to install K Version Manager (KVM). Now if you set KRE_FEED to https://www.myget.org/F/aspnetrelease/ api/v2 and run `kvm upgrade` it will install KRE from the release feed. Now restart VS so that it points the project to latest KRE. In addition you can do that by going to the Properties window of the project and changing the runtime. 

I used the release feed because those are more stable bits. The vnext is updated everytime there is a checkin hence is fast moving

**Comment by heathyates** [comment]
@suhasj Thank you for your prompt replies and willingness to help. I am happy to hear you agree that the issue might be because of using beta2 KRE with beta3+ packages. I have down as you asked: 

1. I have had KVM installed since version beta 1. I deleted the KRE versions related to beta1. 
2. I have set VS for the nightly build https://www.myget.org/F/aspnetrelease/api/v2 
3. I ran `kvm upgrade` and got the following below: 
![kvm](https://cloud.githubusercontent.com/assets/1896424/6066204/fa62cd66-ad30-11e4-814e-ffe8cc9553a9.PNG)

Can you see my steps and please correct me on what I could be doing wrong? I feel with your help @suhasj that this issue is almost resolved. If I tell others who are experiencing it, I will be sure to point them here and give you credit for your hard work and time. Thanks :+1:

**Comment by heathyates** [comment]
@suhasj Thanks!

**Comment by suhasj** [comment]
@heathyates happy to help
