### ISSUE TITLE
Lockout hyphen bug

### ISSUE THREAD

**Issue by tomaszbartoszewski** [aspnet/Identity#439]
We have an issue with a username with a hyphen sign. The AccessFailedCount value is not increasing after login failure. For other users (without hyphen) it is working correctly.

Thanks
Tomasz

**Comment by suhasj** [comment]
@tomaszbartoszewski : I tried with a sample username of `foo-bar-baz` and the access failed count seems to increment as expected. Is there a specific repro you have ? It would be good if you can share a sample repro project or repro steps. I used the web project that is created using 'File --> New Project' in Visual Studio 2015

**Comment by tomaszbartoszewski** [comment]
Hi. I have some example, hopefully it will help.
I created new app in VS2013 and it was working correctly (I'm using SQL SERVER 2012). But I have a bit different config at work so I moved it:
models - we are using int as PK
https://github.com/tomaszbartoszewski/IdentityBug/blob/master/WebApplication1/WebApplication1/Models/IdentityModels.cs
and here is configuration:
https://github.com/tomaszbartoszewski/IdentityBug/blob/master/WebApplication1/WebApplication1/App_Start/IdentityConfig.cs

Let me know if you need any more informations.

Thanks
Tomasz

**Comment by suhasj** [comment]
@tomaszbartoszewski thank you for the sample. The steps I followed

* clone the sample
* Added the following code so that I can register usernames with hyphen

```
// Configure validation logic for emails
            UserValidator = new UserValidator<ApplicationUser, int>(this)
            {
                RequireUniqueEmail = true,
                AllowOnlyAlphanumericUserNames = false
            };
```
* Registered the user `foo-bar@baz.com`
* Tried to login the above user with incorrect password twice

I checked the database and the access failed count was incremented as expected. The change in the sample I see if that you are using `int` as the PK rest seems fine. Can you let me know if you can repro the issue with on the machine with the exact steps as above. The only change then would be the SQL since I am using Localdb

**Comment by tomaszbartoszewski** [comment]
OK, I know the reason. I was migrating from SimpleMembership to Identity so we have already an user with hyphen in name. And you can still log in with his user name, looks like SignInManager doesn't care about configuration. And because of that I was thinking AllowOnlyAlphanumericUserNames is set to false by default - "@" and "." are not alphanumeric as well. However there is a comment "Only allow [A-Za-z0-9@_] in UserNames" but variable name is a bit misleading. I'm going to change my config and it will solve the problem. But this inconsistency between SignInManager and UserManager is probably not good.
Thanks for your time and help, I really appreciate it.
