### ISSUE TITLE
Have an overload of UseIdentity() that takes in a DataProtectionProvider

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#466]
Based on the discussions, we need to have this so that we can pass in the instance pf DataProtectionProvider that can be shared among apps

**Comment by HaoK** [comment]
I've changed my mind a bit.  @divega @blowdart @rustd 

How about we just require a similar line in 5.0 apps that 4.5 apps if they want to be shared:

```
            services.ConfigureIdentityApplicationCookie(options =>
                    options.TicketDataFormat = new TicketDataFormat(dataprotector);
```

Its not actually easy to get this to flow as an IdentityOption, since they are not designed to really to store settings that end up affecting other framework's options.  

And this isn't really that drastically different than something like `UseIdentity(dataProtector)` in terms of complexity, if anything is this more clear what's going on

**Comment by divega** [comment]
I am fine with this. It has the advantage that the line goes in ConfigureServices where we have already moved all configuration tweaking.

What is data protector exactly? I imagine a manually need up instance of the service?

**Comment by blowdart** [comment]
Data Protector provides the encryption, signing, decryption and verification services for auth tickets. 

You'd create one on application startup, although identity would do one for itself if one is not provided.

**Comment by suhasj** [comment]
@Tratcher suggested something similar too. I think this'll work

**Comment by HaoK** [comment]
Okay looks like we are all agreed, so we don't need this overload
