### ISSUE TITLE
RoleManager or UserManager not support Lazy Loading?

### ISSUE THREAD

**Issue by heavenwing** [aspnet/Identity#471]
I write this code:
```
   var role = await RoleManager.FindByNameAsync("Sales");
   var userIds = role.Users.Select(o => o.UserId).ToList();
```

But, role.Users is 0 count, I have to change my code to:
```  
  var role = await RoleManager.Roles.Include(o => o.Users)
                .Where(o => o.Name =="Sales")
                .FirstOrDefaultAsync();
```

I believe that ef7-beta4 have supported lazy loading base of MusicStore code.

**Comment by HaoK** [comment]
@divega is lazy loading supported in EF7?

**Comment by divega** [comment]
@heavenwing EF7 does not support lazy loading, at least not yet. If this was working before it might have been because the Identity API either eager loaded or performed additional queries to load the related entities. In Identity 3 we have changed the behavior to only load the entities that are needed for the implementation of each particular API. This is a performance optimization. 

As a consequences applications should not rely on Identity 3 APIs loading any additional entities as a side effect. You have two choices:

- Use purely Identity APIs to get that data that you need
- Or else issue queries against the EF model using eager loading or issuing multiple queries

For the latter you can easily the IdentityDbContext instance used by Identity in the request from DI. Note that you can also use the `IQueryables` exposed in the manager classes but if you are going to do eager loading via the `Include()` then your queries depend on EF and you are better of just using the actual DbContext.
