### ISSUE TITLE
AddUserManager<TUserManager> should register TUserManager as a service

### ISSUE THREAD

**Issue by PartyArk** [aspnet/Identity#493]
If I create a custom UserManager
```
public class MyUserManager : UserManager<User>
{
    public MyUserManager(IUserStore<User> store) : base(store, ...) { }
}
```
... and then register it in my Startup class:
```
services
   .AddIdentity<ApplicationUser, IdentityRole>()
   .AddUserManager<MyUserManager >()
```

I would then should expect to have it usable in my Controllers I think?

 ```
public AccountController(MyUserManager userManager, SignInManager<User> signInManager)
{
            this.userManager = userManager;
            this.signInManager = signInManager;
}
```
But this won't work: AddUserManager registers the base Interface with the derived class as its implementation.  So you can overwrite the methods of UserManager, but not extend it. The only way to make it work is to register it directly in Startup.cs - 

```
services.AddScoped<MyUserManager>()
[or]
services.AddScoped(typeof(MyUserManager))
```

I suggest that it should be fully extendable, rather than just an alternative implementation.

**Comment by rustd** [comment]
@divega

**Comment by Bartmax** [comment]
https://github.com/aspnet/Identity/issues/215

**Comment by divega** [comment]
@PartyArk With our current implementation this is the expected behavior: `AddUserManager<TUserManager>()` will register the type you provide as the implementation of the UserManager<TUser> service. It will __not__ registerer your custom user manager type as a service type so you won't be able to resolve it from DI. 

Also, your workaround may not do exactly what you expect, e.g.  AddScoped<MyUserManager>() is registering your custom user manager as its own service implementation, so when you resolve it, you will get a completely separate instance from the one that Identity is using for the same request. This might not matter a lot if your custom user manager doesn't hold to any state besides the store, but in the general case it is not safe.

Here is an alternative version of the workaround that should return the same instance regardless of whether you try to resolve `MyUserManager` or `UserMananger<User>`:

``` C#
services.AddScoped<MyUserManager>(p => p.GetRequiredService<UserManager<User>>());
``` 

Now, we have three options here:

1. Not change the behavior but make sure we document it clearly
2. Add the workaround inside the `AddUserManager<TUserManager>()` method so that is just works the way you expected it to work
3. Remove the `AdduserManager<TUserManager>()` method altogether

Note that the reasons we believe the third option might be acceptable are that:

- Many of the motives you could to create your own derived `UserManager<TUser>` in ASP.NET Identity 2.x have disappeared with the introduction of Dependency Injection in 3.0. E.g. in 2.x if you needed to override any of the individual services used by the user manager you had to override some method in your own derived `UserManager<T>`.
- This is just a "sugar" method to make the registration in DI easier. If you have custom needs you can always write your own registration.

Before we decide what option to take, we would like to understand your scenario better, e.g. what was exact your motivation to create a custom `UserManager<TUser>`?

**Comment by PartyArk** [comment]
Hi, first thanks for taking the time to reply.

To get to the point, here's what I think may be a typical scenario.

Let's try to extend our `ApplicationUser` to have addresses associated with it. We'll first create a new `Address` class, and an `Addresses` table in the db with a `UserId` foreign key. We'll plan to have multiple addresses per User, hence the need for a separate table.

First, we'll want to extend `UserStore`. The *Stores seem to be low-level mapping between the database and the application, so we won't put any logic here. Following the lead of the UserStore, `MyUserStore` will look something like this:
````
public class MyUserStore : UserStore {

       [omitted constuctor]

        private DbSet<Address> Addresses => Context.Set<Address>();

        public async Task<IList<Address>> GetAddressesAsync(User user)
        {            
            return await Addresses.Where(a => a.UserId == user.Id).ToListAsync();
        }
}
````
We shouldn't be interacting directly with the Store. Business logic goes in the UserManager. I could create a separate class to manage UserAddresses, but it would be a lot neater to extend the UserManager and know all my methods are in one place. 

The magic of DI allows us to do this quite neatly in the constructor:
````
public sealed class MyUserManager : UserManager<ApplicationUser>
{
        private readonly MyUserStore myUserStore.

        public MyUserManager(IUserStore<ApplicationUser> userStore, .... ) :base(store, .....)
        {
                myUserStore = (MyUserStore)userStore;
        }

        // example: save user and address together
        public async Task<IdentityResult> CreateAsync(User user, string password, Address address)
        {
            var result = await CreateAsync(user, password);
            if (result.Succeeded)
            {
                // use a method from our custom userstore
                return await myUserStore.AddUserAddressAsync(user, address);
            }
            return result;
        }
}
````
And again, that works fine. I have a new method in my `MyUserManager` which allows me to Create a user and its associated address at the same time. Of course, I'd expect to add a number of other methods both to MyUserStore and MyUserManager to change / update / remove addresses.

To register, I can do this:
````
            services.AddIdentity<ApplicationUser, IdentityRole>()
                    .AddEntityFrameworkStores<ApplicationDbContext>()
                    .AddUserStore<MyUserStore>();
                    .AddUserManager<MyUserManager>();
````
What I originally expected was then to have direct access to `MyUserManager` in my MVC Controllers or wherever else there is DI. In fact, I do - as long as I remember to do this:
````
        private readonly MyUserManager myUserManager;
        public AccountController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = (MyUserManager)myUserManager;
        }
````

So, there we have it. I think this will be quite a common scenario. There are other ways of achieving what I want, but it seems to me the extensibility of the Identity framework should be used for this sort of thing. While Addresses will be quite a common scenario, the key here is to allow extensibility with _whatever_ you want to do with your User.

Why go to the bother? Because this way, I know that all the methods I need for interacting with my extended ApplicationUser will be in my extended UserManager. The MyUserManager is a single, predictable interface to the Identity user.

Thanks again.

**Comment by PartyArk** [comment]
It would be helpful to know if the scenario I outlined is a sensible way of extending UserStore / UserManager, or if there's a preferred/better way. Thanks.

**Comment by divega** [comment]
@PartyArk Thank you very much for taking the time to write this up and for trying this. 

After reading what your write up I feel that it is probably worth for us to go with option 2, i.e. add the proper registration for your custom `UserManager` type as part of the `AddUserManager<TUserManager>()` call to make the behavior closer to what customers would likely expect. 

Still, after reading your write up I am also worried that the further you go down this path, e.g. adding arbitrary entities to the Identity model and trying to keep the `UserManager` the central API for managing it, the higher the chances are that you will hit something that we didn't think about and that will require other changes to our code to make it really work. 

In general we err on leaving our code open for extensions (e.g. we don't use the `sealed` keyword very often these days) to avoid artificially blocking customer from doing what they want although it is impossible for us to anticipate every single way things can be extended :smile:

**Comment by PartyArk** [comment]
Great, I'll leave it up to you to decide what to do with my use case, but it may be that you don't actually need to do anything:  the Store / Manager classes are already extensible, and if the Use* methods work; the only 'caution' is that the DI passes around the base Interface rather than the concrete method, so if you want to use them via DI then you have to remember to cast appropriately.

Essentially that may not be worth a re-factoring of the code, if a suitable example is provided.

While I'm commenting, a couple of things you might want to flag elsewhere

1. There's no view for Lockout in the sample, which seems like an omission

2. More importantly, there's an assumption in the Sample that we should not reveal whether a User exists. So, with password retrieval for instance, if you enter a non-existent email it doesn't reveal whether that User actually exists or not. Assuming this is important, it's trivially easy to bypass: if I'm a bad-guy trying to see if user@gmail.com is a valid User, all I have to do is try to register him. If he *is* a registered user, then I'll be told "user already exists". I'm not sure whether there's any sensible workflow to prevent this, but I thought Id' flag it.

**Comment by Bartmax** [comment]
About point 2. Yes this is really bad. I think you should create a separate issue. I hope the templates gets open source soon so we can help with this. Template got a lot of problems/errors.

**Comment by divega** [comment]
@PartyArk we have decided to add the registration for the custom UserManager type. Regarding your other points, could you file separate issues?

**Comment by Pictuel** [comment]
@divega Hi, would it be possible to do the same with the other methods like, AddUserStore and AddUserValidator please?

**Comment by divega** [comment]
@Pictuel I am curious, why do you need this? Does your application use the Identity stores and user validator directly?

**Comment by Pictuel** [comment]
I was a bit ambitious, I maybe don't need that anymore as I'm still searching how to find a correct solution to my needs.
I'm currently working on a method to encrypt values stored through the default identity stores. (https://github.com/aspnet/Identity/issues/516)
I'm able to encrypt all the datas except for the email address that is supposed to be validated with the UserValidator class, that's why I'd like to use it directly to override some methods then use it on my own custom user manager. I'm probably doing something wrong, that's why I'm unsure actually on what I really need in order to achieve my current task.

**Comment by HaoK** [comment]
4e0000163ba5067dcbe79a33f80192623fc4d5f3
