### ISSUE TITLE
Add error message for not configuring a Store

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Identity#501]
Do something like MVC: https://github.com/aspnet/Mvc/blob/faaba481e82f15e83b6ff02241fe2c55e568a9d0/src/Microsoft.AspNet.Mvc.Core/BuilderExtensions.cs#L61

Print out a nice error message when Identity is configured incorrectly.

**Comment by HaoK** [comment]
I think the experience today is that you get whatever stock DI missing required service exception message is.  Do you find that error not descriptive/intuitive enough?

**Comment by BrennanConroy** [comment]
The error says ```InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Identity.IUserStore`1[EmptyToStart.Models.ApplicationUser]' while attempting to activate 'Microsoft.AspNet.Identity.UserManager`1[EmptyToStart.Models.ApplicationUser]'.```

An average user would not know the internals of which services AddIdentity and friends add and would not know what to do.

**Comment by divega** [comment]
To add more background, in the context of ASP.NET Identity the `AddIdentity()` extension method and its friends are considered just sugar methods and we think it is valid to wire up the services manually. Moreover, store writers are encouraged to produce their own sugar `AddXyzStores()` extension and they should be able to do it with minimal friction. Given that, a marker service that any `AddXyzStores()` methods needs to add in order for their stores to avoid an exception seems very strange. On the other hand the store services are generic on user types, so it is hard to think how we could detect whether they have been registered anywhere before they are injected into the constructors of the instances that consume them, e.g. `UserManager<TUser>` and `RoleManager<TRole>`. Last, we could change the signature of `UserManager<TUser>` and `RoleManager<TRole>` so that the store services are not required and then throw a clearer exception from their constructor, but that would dilute the clarity of their contract. 

All in all, I get that these are only semi-strong arguments for not trying to improve on what DI will throw and that the exception from DI is not great. That said, are we ok with adding a layer of indirection everywhere we use DI to make the exceptions better? If yes, can we find a pattern that works and only adds minimal conceptual overhead for people trying to extend our stack?

**Comment by divega** [comment]
(made some edits to make the post above clearer)

**Comment by rustd** [comment]
We considered this and we are not fixing this issue. However, like MVC we will throw if you don't have AddIdentity()

**Comment by kerryjiang** [comment]
I fixed it by adding the line below in ConfigureServices method of Startup:

`services.AddEntityFrameworkStores<YourDbContext>();`

Probably the name "AddEntityFrameworkIdentityStores" is more suitable for this extension method.
