### ISSUE TITLE
How to register custom storage provider?

### ISSUE THREAD

**Issue by simonpbond** [aspnet/Identity#504]
Hello,

I am trying to convert an Identity 2 custom storage provider to work with Identity 3 (without EF).

I'm having difficulty understanding how to register ASP5 middleware for Identity without EF.

At the moment I have done the following:

``` C#
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddRoleStore<MySQL.RoleStore<IdentityRole>>()
                .AddUserStore<MySQL.UserStore<IdentityUser>>()                
                .AddDefaultTokenProviders();
``` 

I'm not sure how I can also include the DI for my Database to be registered also?

I just want to ensure I am registering the middle-ware correctly (hopefully that will solve my problem).
I cannot find any documentation on this and registering EF seems to be done differently.

When clicking 'Register' or the default MVC6 template I am receiving an error of:
"InvalidOperationException: Unable to resolve service for type 'Bondii.Identity.MySQL.MySQLDatabase' while attempting to activate 'Bondii.Identity.MySQL.UserStore`1[Bondii.Identity.MySQL.IdentityUser]'."

My GitHub repository to see my code is:
https://github.com/simonpbond/bondii.identity.mysql

Original storage provider tutorial for Identity 2 - I am trying to upgrade:
http://www.asp.net/identity/overview/extensibility/implementing-a-custom-mysql-aspnet-identity-storage-provider

**Comment by divega** [comment]
You can create your own extension methods to chain after the `AddIdentity()` call, e.g.  

``` C#
            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddSimonsMySqlStores()
                .AddDefaultTokenProviders();
```

It is really up to you whether the method will register all the services needed or whether you want to have registered separately. 

For the default service registration we do in the templates we do have a separate registration for the EF services and also for the specific DbContext that then Identity uses, e.g.:

``` C#
             services.AddEntityFramework() 
                 .AddSqlServer() 
                 .AddDbContext<ApplicationDbContext>(options => 
                     options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"])); 
```

That makes sense in this case because EF and the ApplicationDbContext are usable outside of Identity.
