### ISSUE TITLE
UserManager constructor-overinjection and service locator antipattern

### ISSUE THREAD

**Issue by bitbonk** [aspnet/Identity#559]
The [constructor of `UserManager`](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs#L48-L55) has very many dependencies. It is a case of the [constuctor over-injection antipattern](http://blog.ploeh.dk/2010/01/20/RebuttalConstructorover-injectionanti-pattern/). 

Both of this is a hint that the `UserManager` class does way too much and violates the SRP. The lines of code that this single class has proves this.

Also UserManger depends on `IServiceProvider`, which is a case of the [service locator antipattern](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/). The only reason `IServiceProvider` is injected is to register all tokenproviders that are configured in the TokenOptions. Why not inject `IEnumerable<IUserTokenProvider<TUser>>` instead?

**Comment by slaneyrw** [comment]
Also, I can't see the value of injecting ``IOptions<IdentityOptions>`` instead of just `IdentityOptions``.

This, and the issue raised by bitbionk feels like you are catering for the limitations of the default IoC implementations

**Comment by divega** [comment]
Just found this long standing discussion in my investigation queue. Unfortunately I haven't responded before. 

First, the constructor over-injection link (maybe unintentionally?) points to a rebuttal of the stated anti-pattern which asserts construction injection is generally the way to go. Regardless, I agree with some of the approaches suggested in that article could applicable to ASP.NET Core Identity, e.g. **using singleton lifetime for services that can be singleton can actually help reduce unnecessary allocations and improve throughput**. 

I also agree that **taking an `IServiceProvider` as a dependency and using service locator** should be avoided if possible. 

The key issue in the original post seems to be how `UserManager` concentrates a number of different responsibilities. Although there is some separation in the form of interfaces in the underlying persistence layer, the actual implementation lives in very few types and `UserManager` is a façade over all that functionality. 

The choice of doing this may be considered a bit arbitrary, but it does provide some simplicity in the programming model, e.g. there is a single type on which you can find (and override, at least for simple scenarios) most actions around the `User` aggregate. 

An easy parallel to make is how some developers would choose to define a repository interface to abstract all persistence concerns for that type form the application, while some other developers could possibly prefer to "split hairs" and separate each of the CUD operations into their own type. 

Overall I do not see an absolute truth but if there are specific areas in which we have gone too far in concentrating responsibilities in `UserManager` and if there are tweaks we can make to getter better factoring it would be nice to get the feedback. 

Removing the milestone so that we can discuss this in triage. It seems at this point the ship has sailed for certain kind of changes but we can consider improvements in the next major release.

**Comment by divega** [comment]
**Note for triage:** Removing the milestone so that we can discuss making improvements in our factoring and service lifetimes. It seems at this point the ship has sailed for certain kind of changes but we can consider improvements in the next major release.

**Comment by blowdart** [comment]
It is what it is, managers extend over everything like an octopus, giving a central entry point. Whilst this isn't great from a no god object PoV it is easy from a users perspective. And it's the ordinary users that we're trying to address.
