### ISSUE TITLE
UserClaimsPrincipalFactory.CreateAsync and authenticationType param

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#625]
The XML docs for this has a authenticationType param, but the implementation does not. I think it should have an authenticationType since that's how you can populate the ClaimsIdentity with things like "password" or "2fa" so the app knows how the user authenticated (and perhaps change it's behavior accordingly).

Using Options.Cookies.ApplicationCookieAuthenticationScheme is not very useful and arguably is mis-using the auth type param on the ClaimsIdentity.

**Comment by HaoK** [comment]
I'll remove the doc comment, basically in 3.0 the auth stack has changed the contract to be around creating principals now, unlike in 2.0 which was about creating ClaimsIdentities.  You are free to set whatever authentication type you want in any of the identities your principle creates, we do not look at the authentication type for anything anymore, as authentication handlers are now responsible for producing principals for a particular authenticationScheme and not tied to any particular authenticationType which was different in 2.0....  That's why it was dropped from the interface.
