### ISSUE TITLE
GUIDs for security stamp

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#626]
So a GUID is being used for the security stamp. On windows that has ~96 bits of entropy (according to @GrabYourPitchforks), but on linux there's no guarantee (unless that's changed and something in CoreCLR addresses this). So I worry that somehow the lack of entropy could be used to abuse ASP.NET Identity if/when running on linux, and perhaps crypto RNG is better.

If this is still an issue, then it will be true of any DNX code (perhaps in ~/security repo as well -- i've not checked if there is any Guid.NewGuid code being used there).

**Comment by GrabYourPitchforks** [comment]
They actually have 122 bits of entropy. Regardless, as of the last time I looked at the code base, the security stamp doesn't need to be secret or unpredictable. It's used simply to version existing payloads like refresh tokens or reset tokens. If the security stamp in the incoming refresh token doesn't match the security stamp in the DB, then the request should be rejected. The refresh token in the incoming request should be integrity-protected (the DataProtection APIs take care of this automatically) so that the client can't mess with the embedded security stamp.

**Comment by brockallen** [comment]
Just raising it as an issue to be considered given how the guid is being used.

As for:

> the security stamp doesn't need to be secret or unpredictable

IIRC, the security stamp is the main input to the TOTP (as well as time, but that's well known-ish for 2FA given the steps) and thus if an attacker has just read-only access to the DB they can predict the SMS code for 2FA. I guess in theory if the security stamp is also predictable then it's also potentially a vector.

I'm sure it's a remote vector and I'm certainly not motivated enough to work at cracking it, but someone else might be :)

Again, just mentioning it so someone smarter than me can think about it.

**Comment by GrabYourPitchforks** [comment]
Ah, I thought there was an additional source of entropy for the TOTP code paths. This is something @HaoK and @blowdart should look at.

**Comment by brockallen** [comment]
Same issue exists in AspId v2 :)

**Comment by blowdart** [comment]
Darnit Linux :) Yea, we should switch to an CNG based random array of bytes, of the maximum size the TOTP algorithm uses. @HaoK

**Comment by HaoK** [comment]
Are we backloging this @blowdart ?

**Comment by blowdart** [comment]
I guess so, it's too big a change to make now unfortunately.

**Comment by PinpointTownes** [comment]
A big change? Heh, why?

Using `RandomNumberGenerator` doesn't seem really complicated. And if switching to a non-GUID format string is not an option, nothing prevents you from creating a GUID using the bytes generated by the RNG (instead of using `Guid.NewGuid()`), like you already do for the session middleware.

**Comment by HaoK** [comment]
The change being considered would be moving to a per login factor secret. 

The guid thing wasn't as big of a deal.

**Comment by HaoK** [comment]
Clearing for triage

**Comment by blowdart** [comment]
In addition we should change old TOTP entropy to use something other than security stamps, because there's a risk that people leak those.

**Comment by Eilon** [comment]
@blowdart - this is a pretty old bug. Do we plan to fix in 2.1.0? If not, recommend moving to 2.2.0 or closing.

**Comment by HaoK** [comment]
Ah I missed this one since it wasn't assigned to me...  it should be an easy fix, one liner type, I'll get a PR out for this today.

**Comment by HaoK** [comment]
Well there's 2 parts to this... @blowdart are you ok if we split this work?  basically change how we generate security stamps now to move away from guids, but leave the TOTP entropy to be against security stamps for 2.1

**Comment by HaoK** [comment]
@blowdart how do you feel about return a new authenicator key whenever we want to generate new security stamps?

https://github.com/aspnet/Identity/blob/dev/src/Core/UserManager.cs#L2226

**Comment by blowdart** [comment]
Both work.

**Comment by HaoK** [comment]
Filed https://github.com/aspnet/Identity/issues/1711 to track looking into moving to per login factor secret which is more involved (and likely requires schema changes)
