### ISSUE TITLE
UserManager.FindByXXX function returns with user.Roles.Count = 0

### ISSUE THREAD

**Issue by Sally-Xu** [aspnet/Identity#684]
When I use UserManager to find a user, the returned user.Roles is always empty. This was not the case before EF 7.  Not sure this is the bug in UserManger or EF 7 bug.

Testing code:
var user = await UserManager.FindByIdAsync(id);   // this user has roles
var roleCount = user.Roles.Count;  ----- this is always 0 

I'm using 
"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",

**Comment by brockallen** [comment]
Does EF7 do lazy loading? Also, you're sort of going around the AspId programming model -- there are store interfaces for loading specific kinds of data.

**Comment by MaximRouiller** [comment]
@brockallen https://github.com/aspnet/EntityFramework/wiki/Roadmap#high-priority-features

Nope. No lazy loading yet but it's in the roadmap.

**Comment by brockallen** [comment]
So then that's my guess as to why @Sally-Xu is seeing this behavior. But still, you should use the designated APIs for loading the designated things from AspId.

**Comment by Sally-Xu** [comment]
I found Eager loading with "Include" is already implemented in EF7. If UserStore.FindByXXX function use "include(u=>u.Roles) to get the roles back, this problem can be solved right now.

**Comment by brockallen** [comment]
@Sally-Xu just so you know, you're now bypassing the storage abstraction for this and not using the formally designed API for loading that data. If you're cool with that, then godspeed.

**Comment by divega** [comment]
:+1: to @brockallen's comment. While you are free to execute your own queries against the EF model underlying the default Identity stores, the Identity APIs (I would say UserManager and RoleManager and not the stores) are the recommended way of interacting with Identity. These should give you the correct data and are independently of the store provider in use.

FWIW, the EF store providers for Identity 2.x used to load a user and all its associated data upfront. In order to make things more efficient we changed that in 3.0 to defer the loading of specific data into memory until it is required. The implementation uses explicit queries rather than relaying on any transparent lazy loading mechanism.
