### ISSUE TITLE
RoleManager.FindByNameAsync does not include Users and Claims

### ISSUE THREAD

**Issue by arashnorouzi** [aspnet/Identity#690]
When I use RoleManagerto find a role, the returned role.Claims and role.Users is always empty. 
I have checked Identity source code and in line 270 on  RoleStore.cs we have: 
```
public virtual Task<TRole> FindByNameAsync(string normalizedName, CancellationToken cancellationToken = default(CancellationToken))
        {
            cancellationToken.ThrowIfCancellationRequested();
            ThrowIfDisposed();
            return Roles.FirstOrDefaultAsync(r => r.NormalizedName == normalizedName, cancellationToken);
        }
```
It seems Claims and Users are not included by default.
EF7 lazy loading is not implemented yet and I was wondering if Identity should load these explicitly. 
To get it working for now I had to create my own RoleManager, register it on startup and 
override the FindByNameAsync method like this: 
```
 public override async Task<MyRole> FindByNameAsync(string roleName)
        {
            if (roleName == null)
            {
                throw new ArgumentNullException(nameof(roleName));
            }
            var role = await Roles.Include(x => x.Claims).FirstOrDefaultAsync(x => x.NormalizedName == NormalizeKey(roleName));
            return role;
        }
```

**Comment by HaoK** [comment]
Identity's default EF provider is no longer including anything, since identity provides APIs to directly access Role claims and role users via the RoleManager api.  You can certainly override the default implementation to include things like this if desired, but this is no longer behavior we are supporting by default...

@divega might be able to provide more guidance on the best way to approach this

**Comment by HaoK** [comment]
See the comments in a similar issue for more guidance: https://github.com/aspnet/Identity/issues/689#issuecomment-171119975
