### ISSUE TITLE
UserManager.FindByName does not load custom properties of UserIdentity

### ISSUE THREAD

**Issue by erlimar** [aspnet/Identity#724]
Package versions:

``` json
{
    "dependencies": {
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "EntityFramework.SQLite": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
        "Microsoft.AspNet.Authorization": "1.0.0-rc1-final",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
        "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
        "Microsoft.AspNet.Session": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
        "Microsoft.Extensions.Caching.Memory": "1.0.0-rc1-final"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {}
    }
}
```

My Startup services configuration:

``` cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        var ef = services.AddEntityFramework();
        ef.AddSqlServer().AddDbContext<AuthContext>(options =>
        {
            options.UseSqlServer(dbConnectionString);
        });

        services.AddIdentity<User, IdentityRole>(options =>
        { /* ... */ })
        .AddEntityFrameworkStores<AuthContext>()
        .AddDefaultTokenProviders();
    }
}
```

My Context:

``` cs
public class AuthContext : IdentityDbContext<Model.User>
{
    public DbSet<UserProfile> UserProfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<UserProfile>(b => 
        {
            b.HasKey(p => p.UserId);
            b.HasOne(p => p.User)
             .WithOne(u => u.Profile)
             .HasForeignKey<UserProfile>(p => p.UserId);
        });
    }
}
```

My Model:

``` cs
public class User : IdentityUser
{
    public UserProfile Profile { get; set; }
}

public class UserProfile
{
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public string UserId { get; set; }
    public User User { get; set; }
}
```

I am adding a user as follows:

``` cs
public class Account : Controller
{
    public Account(UserManager<User> userManager, AuthContext authContext)
    {
        UserManager = userManager;
        AuthContext = authContext;
    }

    private UserManager<User> UserManager { get; set; }
    public AuthContext AuthContext { get; set; }

    [HttpPost]
    public async Task<IActionResult> SignUp(SignUpViewModel model)
    {
        if (ModelState.IsValid)
        {
            /* ... */
            var user = new User
            {
                UserName = tempUserName,
                Email = model.Email
            };

            user.Profile = new UserProfile
            {
                FirstName = model.FirstName,
                LastName = model.LastName
            };

            var result = await UserManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            { /* ... */ }
        }

        return View(model);
    }
}
```

At some point I need to recover data from a user, and do as follows:

``` cs
var user = await UserManager.FindByNameAsync(userName));

/* ... */

var firstName = user.Profile.FirstName;
```

Then I get an error:

```
An unhandled exception occurred while processing the request.
NullReferenceException: ...
```

I realized that `user.Profile` is null.

Out of curiosity, I tried to load the profile alone without even assign to any variable.

``` cs
var user = await UserManager.FindByNameAsync(userName));

// HACK: ???
AuthContext.UserProfiles.SingleOrDefault(p => p.UserId == user.Id);
/* ... */

var firstName = user.Profile.FirstName;
```

And suddenly my variable previous `user` was the value of `user.Profile` filled out correctly.

> **I noted that the data are entered correctly in the database.**

**Comment by rustd** [comment]
Accessing the child entities through the DbContext is fine. 
For the future add a new extensibility point which loads the child entities. (include extra data)

**Comment by divega** [comment]
Just to add a bit more detail: as a performance optimization ASP.NET Core Identity currently only loads the entities related to a user or a role as needed to satisfy API calls. I.e. it won't load related entities (not even the built-in ones) eagerly on a method call like such as `FindByName()` because the find methods are only required to return the root. 

At this point issuing queries against the DbContext is the recommended way to load related data. If you want to abstract this from the application code you can extend both the Identity store and manager classes to add methods to retrieve and return your custom related data.

**Comment by iberodev** [comment]
I am experiencing a similar situation where I can see when debugging that sometimes the same method 

    var userEntity = await _userManager.FindByNameAsync(username);

is returning the user with its navigation properties and sometimes it is not. 
Thanks @divega for highlighting that because that might be the reason.

Just to clarify, it's like using lazy loading mode (even when in AspNet Core is not enabled nor supported yet as far as I know) in a way where if the `userEntity` (the IdentityUser instance) is doing something with the `userEntity.Roles` it will fetch the Roles, but if there is no explicit interaction with `userEntity.Roles` in the code then it's value will be `null`?

This "magic" has had me scratching my head for a while :)
Especially because I am using a javascript front-end that was relying on a JSON object `userEntity` with all its navigation properties, and sometimes these were `null`.

I will follow your advice and use my own repositories accessing the dbContext to retrieve the `User` explicitly including what I need.

**Comment by ch-hristov** [comment]
This is a huge problem with entity framework as you literally cannot retrieve the virtual properties.

**Comment by ch-hristov** [comment]
And by the way this is in direct conflict with your implementation of Entity Framework! It's absolutely NOT CLEAR what is happening!!

**Comment by urbanhusky** [comment]
Why is this issue closed? 
I do think it is rather ugly and unsafe (encapsulation etc.) to have to manually include required referenced entities, when they are part of the user identity. 

Instead of being able to rely on `await userManager.FindByNameAsync(username)` we have to wrap that in a separate service and remember that we cannot use `UserManager` for reading?

**Comment by Janidbest** [comment]
I have 4 related entities ( we want to leave aspnetusers table flexible for any future changes in the framework), I'm sure this will be grow more soon, having context to use to include related data always a performance constraint. The aspnet identity framework should support to include the related entities when wanted.
