### ISSUE TITLE
Multiple operations in a single transaction is broken.

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Identity#739]
It is currently impossible (or at least very difficult) to 1. create a user, 2. add the user to a role, and 3. perform some custom actions all within one transaction using the built-in classes.

I'm almost there by doing the following:
1. Set UserStore.AutoSaveChanges = false 
2. Do multiple operations on user
3. Call DataContext.SaveChanges.

However, the problem is:
The process of creating a user calls UserStore.CreateAsync(), which adds the user to the context like so:
````
this.Context.Add<TUser>(user, GraphBehavior.IncludeDependents);
````

But then the process of adding a user role calls UserStore.UpdateAsync(), which changes the user's state in the context by running this line:

````
this.Context.Update<TUser>(user, GraphBehavior.IncludeDependents);
````

So then when you go to save changes, you get a SQL error because it's trying to UPDATE the user rather than INSERT the user (it actually tries to INSERT the UserRole first, because of dependencies).

**Comment by HaoK** [comment]
Are you using the user manager APIs and setting AutoSaveChanges to false?  Basically if you turn off AutoSaveChanges the expectation is that you are probably not going to want to use the UserManager APIs, since those are implemented basically by calling some set method on the store, and then update on the user which explicitly save changes.  

Typically you would want to write your own extensions that do not call user.update until you are ready.
