### ISSUE TITLE
Custom UserStore for Identity3.0

### ISSUE THREAD

**Issue by leo9223** [aspnet/Identity#760]
can I use this --> http://www.asp.net/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity

tutorial to have custom user store for identity3.0?

tutorial specifying that it is for identity2.0 I want to know will it also work for identity3.0?

Thanks

**Comment by blowdart** [comment]
@Rick-Anderson One for you again.

**Comment by Rick-Anderson** [comment]
@danroth27 please prioritize

**Comment by simonpbond** [comment]
There would be nothing better than a pure SQL or Dapper example implementation : )

**Comment by musabsudan** [comment]
The article is really good, I wish if it can be updated soon to Identity 3 and if you added  a pure custom SQL implementation that doesn't depend on the EF models.

Everyone seems to have the same struggle when integrating Identity in legacy systems back-ends and the guys here thinks that we have an empty database to throw their implementation in. 

Many times I preferred to throw away Identity and resort to simple authentication because I work with lots of legacy back-ends that the companies invested millions in and they have no way to change it.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/1162
