### ISSUE TITLE
How to make Identity helper classes use existing DbConnection?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#802]
Hi,

I noticed through my logs, Identity helper classes (e.g. `UserManager`) open a new connection for each method.
This can be 10 new connections in a single API request.
Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

Is it possible to config Identity helper classes use existing DbConnection?
If it's not, can we please add this very needed functionality?

Thanks,
Doron

**Comment by divega** [comment]
Identity methods should be using the same instance of a `DbContext` (an `ApplicationDbContext` in an application based on the default templates) within a request. For this to work, the `DbContext` in question has to be registered as a scoped service, e.g. using the `AddDbContext<TContext>()` method.

Each `DbContext` will only use one instance of `DbConnection` but by default it is true that it will open and close it as needed, even within the same request. In order to override this you can open the connection explicit in the beginning of the request, e.g. you could do this in the controller's constructor:

``` C#
    myContext.Database.OpenConnection(); // myContext is a constructor parameter and resolved by DI
```

Then the connection should remain open until you close it explicitly or the scoped context is disposed.

> Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

I am not sure what you mean by this.

**Comment by gdoron** [comment]
Thanks for the answer @divega,
> but by default it is true that it will open and close it as needed, even within the same request. In order to override this you can open the connection explicit in the beginning of the request, e.g. you could do this in the controller's constructor.

I hope you classify it as a bug...

A. I can't open the connection asyncly in constructors.
B. I don't want to open a connection in each and every request, some of my actions are cache-able, meaning there will be absolutely 0 requests to the DB.
C. It's a bit awkward.

What is the reason it was designed this way?

>Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

>-I am not sure what you mean by this.

I meant that if there're changes still not flushed to the DB in the connection used by DbContext, the new connection used by UserManager wouldn't not see them.
Am I right?

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework#5147
