### ISSUE TITLE
UseIdentity() is affecting API pipeline

### ISSUE THREAD

**Issue by ravero** [aspnet/Identity#842]
In my ASP.NET Core RC2 project I mixed controllers for Web and API. Web Controllers use the default routing while API controllers uses the Route Attributes.

One of my API's returns an IActionResult that either can return BadRequest(), Unauthorized() and Json(). Before adding Identity to the project it was working fine, but after adding it returning either *BadRequest* or *Unauthorized* is returning the HTML for the Home/Index Action method, even though it's not being processed as I could state by debugging.

If I comment **UseIdentity** from the Configure in Startup it goes back to normal processing. Has anyone found this sort of problem?

**Comment by blowdart** [comment]
UseIdentity wires up cookie middleware, which in turn takes over the 401/403 etc. This is by design.

You're mixing up HTML pages and API Controllers, and that's painful. 

You have a couple of options, you can tell cookie middleware not to be automatic, and then specify the cookie scheme on your HTML controllers, e.g.

    [Authorize(ActiveAuthenticationSchemes = "Cookie")]

Or write authentication middleware for your API scenarios, and use that rather than hard returning statuses, again selecting it with the ActiveAuthenticationSchemes in the authorize attribute.
