### ISSUE TITLE
Customize Error Messages

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#86]
What is the best way to customize error messages coming from the FX as an application developer

**Comment by mderriey** [comment]
Hi,

I'm sorry if this is a silly question as you guys may not be in touch with the non-ASP.NET 5 of ASP.NET Identity.

Do you know if there's any chance that this could be backported in the initial ASP.NET Identity - the one on CodePlex? It's very hard to identify errors in the `IdentityResult` class since it's only based on the resource messages.

Thanks

**Comment by ltvan** [comment]
At least please provide a static method like `IdentityResult.SetResourceProvider(IIdentityResultResourceProvider provider)`. Is there any plan to incorporate this to version 2.x?

Thanks

**Comment by yigith** [comment]
Any update on this issue?

**Comment by DianaKoenraadt** [comment]
Same here, looking to translate IdentityResult.Errors in Identity 2.x
