### ISSUE TITLE
Should you make IUserStore<TUser> covariant?

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Identity#861]
In ASP.NET Identity v2 I'm getting grief casting between IUserStore interfaces when using IdentityUser inheritance.  I believe this is due to the various IUserStores not being covariant.

In the following code, my ChildApplicationUserStore class cannot call the base constructor without casting IUserStore<ChildApplicationUser> to IUserStore<ApplicationUser<CustomIdentityUserLogin>>.  If IUserStore<TUser> was covariant is believe that it will cast implicitly

Note the change to the IdentityUserClaim type parameter - this is the reason for the inheritance chain

```c#
class ApplicationUser<TUserLogin> : IdentityUser<
    string, 
    TUserLogin, 
    IdentityUserRole, 
    CustomIdentityUserClaim> 
    where TUserLogin : IdentityUserLogin
{
}

class ChildApplicationUser : ApplicationUser<CustomIdentityUserLogin> 
{
}


class ApplicationUserManager<TUserLogin> : UserManager<ApplicationUser<TUserLogin>>
{
    public ApplicationUserManager(IUserStore<ApplicationUser<TUserLogin>> userStore) 
        : base(userStore)
    {
    }
}

class ChildApplicationUserStore : ApplicationUserManager<CustomIdentityUserLogin>
{
    public ChildApplicationUserStore(IUserStore<ChildApplicationUser> store) 
        : base(store)   // <-- Won't compile without "as IUserStore<ApplicationUser<TUserLogin>>
    { 
    }
}
```

**Comment by magnusbakken** [comment]
IUserStore<TUser> can't be covariant because there's a method on it where the TUser type parameter is used as input. In fact this is true of almost all the operations on the interface. This is an important rule for the variance feature in the C# type system.

If you think about it you'll see why this restriction is in place. Consider this scenario:

```c#
public class A { }
public class B : A
{
    public string UserId { get; set; }
}

public class UserStoreB : IUserStore<B>
{
    public Task<string> GetUserIdAsync(B user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.UserId));
    }

    // ...
}

IUserStore<A> store = new UserStoreB(); // Would be legal if IUserStore were covariant.
A user = new A();
string userId = await store.GetUserIdAsync(user, cancellationToken);
```

You're now calling an implementation of GetUserIdAsync that expects a variable of type B, but instead it receives an A. This can't possibly work, since instances of A don't even have the UserId property that's being used in the method.

I think you need to rethink your architecture here. I'm not sure I understand exactly what it is you're trying to accomplish.
