### ISSUE TITLE
What is the purpose of navigation property initialization with List<T> instances?

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Identity#871]
What is the purpose of navigation property initialization with List<T> instances as Entity Framework uses HashSets? Or I miss something.

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUser.cs#L154
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUser.cs#L159
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUser.cs#L164

**Comment by HaoK** [comment]
@divega any thoughts?

**Comment by jvelezc** [comment]
One use is to prevent null exceptions which i have gotten when i don't initialize them.

**Comment by divega** [comment]
This went under the radar. AFAIR EF will only instantiate a `HashSet<T>` if the property isn't already initialized, so it is unlikely that the `Lists<T>` are being replaced. 

I think we can switch to `HashSet<T>` or even consider not initializing the properties here. 

Both changes could potentially have performance advantages:
- `HashSet<T>` is more efficient for performing contains checks in memory, which are common in property fixup 
- Deferring the intialization until EF materializes could mean that we end up creating less objects in some scenarios

However both could be breaking changes for customers using the underlying EF model directly, because they could write code that relies on the navigation properties: 
- being instances of `List<T>` 
- not being null (I suspect this could be more common)

**Comment by divega** [comment]
Clearing up so that we can discuss if we want to do anything in triage.

**Comment by HaoK** [comment]
We discussed this and decided against changing this

**Comment by xperiandri** [comment]
Explain what you mean, which change

**Comment by divega** [comment]
@xperiandri see my previous comment at https://github.com/aspnet/Identity/issues/871#issuecomment-236137533. In summary, when we discussed this, the consensus was that the theoretical advantages of either switching initialization to `HashSet<T>` or removing the initialization would offset the potential breaking change impact.

**Comment by xperiandri** [comment]
So now you put lists into properties whenever is located there even if they are initialized, don't you?

**Comment by divega** [comment]
@xperiandri I am not sure what you mean but they are initialized inline and since they are read-only properties any consuming code or EF Core code will just use those lists.
