### ISSUE TITLE
Does TwoFactorSignIn contain a bug or am I configuring Identity incorrectly?

### ISSUE THREAD

**Issue by CamiloTerevinto** [aspnet/Identity#981]
Plase refer to [Does Identity Core TwoFactorSignIn contain a bug?](http://stackoverflow.com/questions/39746258/does-identity-core-twofactorsignin-contain-a-bug)

**Comment by blowdart** [comment]
Copying the stack overflow issue, because a refer isn't that useful when triaging.

This is a very annoying problem, I'm setting up cookies authentication on my asp.net core project and sometimes this error occurs and sometimes it doesn't!

There is no pattern! It just starts throwing the error and suddenly it stops, then start again...

The exception is:

InvalidOperationException: No authentication handler is configured to handle the scheme: MyAuthScheme
This is really really annoying! Here is my Startup.cs

public class Startup
{
    public const string AuthenticationSchemeName = "MyAuthScheme";

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

        services.AddMvc();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IHttpContextAccessor httpContextAccessor)
    {
        loggerFactory.AddConsole();

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
            app.UseBrowserLink();
        }

        app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            AuthenticationScheme = AuthenticationSchemeName,
            LoginPath = new PathString("/login"),
            AutomaticAuthenticate = true,
            AutomaticChallenge = true,
            SlidingExpiration = true,
        });

        app.UseStaticFiles();
        app.UseMvc();
    }
}
And this is my authentication code:

await HttpContext.Authentication.SignInAsync(Startup.AuthenticationSchemeName, new ClaimsPrincipal(new ClaimsIdentity(claims, "Cookie")));

**Comment by HaoK** [comment]
I'm not sure what you mean by TwoFactorSignInAsync sets the username 4 times.

So this method is what does sign in: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L78

SignIn manager does some work around verifying the two factor code, and the user, but the actual application cookie generation is done by the UserClaimsPrincipalFactory.  Perhaps you are looking at the wrong cookie (there are 4 of them)  In general its only the application cookie that you should care able, the rest are there for identity APIs to work

**Comment by CamiloTerevinto** [comment]
Hello @HaoK,

If I debug right after ` var result = await _SignInManager.TwoFactorSignInAsync("Email", model.Code, false, model.RememberBrowser);` the HttpContext.User property contains 4 times exactly the same claim:

{http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: MYGUID}

Thus, either how I set up Identity in Startup is wrong or the 1.0.0 version of TwoFactorSignInAsync does not put the expected claim type "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"

**Comment by HaoK** [comment]
Can you make sure that AutomaticAuthenticate is off for all of the cookie middleware other than the ApplicationCookie (inside of IdentityOptions.Cookies.XyzCookie)

**Comment by CamiloTerevinto** [comment]
@HaoK,

AutomaticAuthenticate is a bool, and I am not setting it explicitly in my code, so my guess is that it's false by default? Not sure where can I check it apart from ConfigureServices

**Comment by HaoK** [comment]
What version of the packages are you using, there was a bug fixed in older versions where the defaults used to be true, you can turn all of the AutomaticAuthenticates to false other than the Application if don't want to upgrade

**Comment by CamiloTerevinto** [comment]
I have no problem upgrading, I am even on EF Core 1.0.1 already. But I have the latest stable as per Nuget (1.0.0). I'll try turn them off explicitly and see what it does

**Comment by HaoK** [comment]
The defaults should be set to off: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs

**Comment by CamiloTerevinto** [comment]
I followed the link provided and changed the Identity setup to this:

```
services.AddIdentity<User, Role>(options =>
{
    options.Cookies.ApplicationCookie.CookieHttpOnly = true;
    options.Cookies.ApplicationCookie.CookieSecure = CookieSecurePolicy.Always;
    options.Cookies.ApplicationCookie.LoginPath = "/User/Login";
    options.Cookies.ApplicationCookie.LogoutPath = "/User/Logout";
    //..............
```

Now after a successful "TwoFactorSignInAsync", HttpContext.User contains 0 identities/claims so not even my workaround works. I checked and all but ApplicationCookie have `AutomaticAuthenticate = false`

**Comment by HaoK** [comment]
Just to clarify expectations, assuming TwoFactorSignIn returned success, it should be setting a cookie which contains the application cookie which will have the user on the next request.  Is that what you are seeing?  I'd also try getting rid of any HttpOnly/Cookie secure extraneous settings for now.

**Comment by CamiloTerevinto** [comment]
Using this
 ```
var result = await _SignInManager.TwoFactorSignInAsync("Email", model.Code, false, model.RememberBrowser);
if (result.Succeeded)
{
    User user = await userManager.GetUserAsync(HttpContext.User);
}
```

I'd expect that if I enter the if it's because all is good, the user entered the correct code and etc. Under normal "_SignInManager.PasswordSignInAsync" this is true; however, for TwoFactorSignInAsync I get null. 
I am now debugging TwoFactorSignInAsync: [SignInManager L379](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L379)

twoFactorInfo = good, retrieved the expected entity
user = good, found the user from the database
error = null, all is good so far
VerifyTwoFactorTokenAsync = true
RememberTwoFactorClientAsync =>
    userId = good
    rememberBrowserIdentity = good
    await SignInAsync = ? not sure what happens there
await SignInAsync (OUTSIDE RememberTwoFactorClientAsync) =>
   userPrincipal = good, contains 3 claims: NameIdentifier, Name and SecurityStamp and all correspond to my user
   await SignInAsync = ? again, not sure what happens there

GOING BACK (all TwoFactorSignInAsync apparently ran fine hence result.Succeeded == true) => HttpContext.User contains absolutely no claims.

**Comment by HaoK** [comment]
Again, two factor sign in if successful, means the NEXT request will have the User set.  Authentication for the current request has already happened.  None of the SignIn's have no effect on the current request.

**Comment by CamiloTerevinto** [comment]
Ahhh, I now get what you are saying. I did not know that. In fact, I never really saw that mentioned anywhere. 
Ok, I removed the get user part for that action and all is working fine, the redirection is already authorized properly. Thank you for your time

**Comment by inexuscore** [comment]
Can someone please, for the love of god, provide an example project for a basic 2FA setup in **Web API 2**. I'm using **Identity 2.2.2** and I need to implement 2FA ASAP, I'm already behind schedule and I need this NOW. Been struggling with this for days and the MVC5 template from Visual Studio 2017 wasn't helpful.

The **SignInManager.PasswordSignInAsync()** method works fine, it returns **RequiresVerification**. But I'm not sure what to do from there.

In my **AuthorizationServerProvider** class, in the **GrantResourceOwnerCredentials()** method, what do I do after receiving a status of _RequiresVerification_, do I have to sign the user in by generating the user identity - for the _SignInManager_ to work properly - or do I set an error on the context and return. What I need to do is this: if the **/token** end-point results in _RequiresVerification_, return an error to notify the client (angular app) that the user needs to verify the 2FA security code. Then I generate and send the code, and display some UI for verification. The user receives the code, sends it to another end-point and it gets verified successfully. But then when I try to call **SignInManager.TwoFactorSignInAsync()** it always fails with a status of **Failure**. 

This is my code:
```
public override async Task GrantResourceOwnerCredentials(OAuthGrantResourceOwnerCredentialsContext context)
{
    var user = await UserManager.FindAsync(context.UserName, context.Password);
    if (user == null)
    {
        context.SetError("invalid_grant", "The user name or password is incorrect.");
        return;
    }

    var signInResult = await ServiceContext.SignInManager.PasswordSignInAsync(context.UserName, context.Password, isPersistent: true, shouldLockout: false);

    // other statuses .. removed for brevity

    if (signInResult == SignInStatus.RequiresVerification)
    {
        var code = await UserManager.GenerateTwoFactorTokenAsync(user.Id, "Email Code");
        IdentityResult result = await UserManager.NotifyTwoFactorTokenAsync(user.Id, "Email Code", code);
                    
        if (!result.Succeeded)
        {
            context.SetError("two_factor_error", "failed to send 2FA code");
            return;
        }
        else
        {
            // user needs to verify security code
            context.SetError("requires_verification");
            return;
        }
    }
}
```

I'm generating and sending the code using the UserManager class because the **SignInManager.SendTwoFactorCodeAsync()** method doesn't work (User Id not found).

And this is how I verify the security code in another end-point:
```
[HttpPost]
[AllowAnonymous]
[Route("VerifySecurityCode")]
public async Task<IHttpActionResult> VerifySecurityCode(VerifySecurityCodeModel model)
{
    try
    {
        var user = await UserManager.FindAsync(model.UserName, model.Password);
        if (user == null)
            return BadRequest("username or password is invalid");

        var isTokenValid = await UserManager.VerifyTwoFactorTokenAsync(user.Id, "Email Code", model.Token);
        if (!isTokenValid)
            return BadRequest("Invalid token. try again");

        // this returns empty GUID
        //var userId = await ServiceContext.SignInManager.GetVerifiedUserIdAsync();

        // this sets the 2FA browser cookie, but doesn't actually sign-in
        //await ServiceContext.SignInManager.SignInAsync(user, isPersistent: true, rememberBrowser: true);

        // this always returns SignInStatus.Failure
        var result = await ServiceContext.SignInManager.TwoFactorSignInAsync("Email Code", model.Token, isPersistent: true, rememberBrowser: true);

        return Ok("Security code verified successfully");
    }
    catch (Exception ex)
    {
        return InternalServerError(ex);
    }
}
```
I'm getting the user by username and password again, because for some messed up reason, the **SignInManager.GetVerifiedUserIdAsync()** method returns an empty GUID. But the **SignInManager.HasBeenVerifiedAsync()** returns true (?!).

I'm nearly there, it shouldn't be this difficult, I think I'm missing something here. What I want is this:

- The user sends a POST request to **/token** with their username/password
- If 2FA is enabled (confirmed email, or a verified phone number), we don't sign the user in, but require them to verify the security code first. They shouldn't be able to request ANY resource (end-point) until they have verified their 2FA code
- We generate the code and send it via email/sms. The user verifies the code, and is signed-in. Of course a 2FA cookie should be set at this point to remember the browser/device. We don't want them to go through 2FA on subsequent requests.

This is my **Startup.cs** config:
```
// Configure the db context, user manager and signin manager to use a single instance per request
app.CreatePerOwinContext(SurveyContext.Create);
app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);

OAuthAuthorizationServerOptions OAuthServerOptions = new OAuthAuthorizationServerOptions()
{
    AllowInsecureHttp = true,
    TokenEndpointPath = new PathString("/token"),
    AccessTokenExpireTimeSpan = TimeSpan.FromDays(7),
    Provider = new AuthorizationServerProvider()
};

// Configure the application for OAuth based flow
PublicClientId = "self";
OAuthOptions = new OAuthAuthorizationServerOptions
{
    TokenEndpointPath = new PathString("/Token"),
    Provider = new ApplicationOAuthProvider(PublicClientId),
    AuthorizeEndpointPath = new PathString("/api/Account/ExternalLogin"),
    AccessTokenExpireTimeSpan = TimeSpan.FromDays(7),
    AllowInsecureHttp = true
};

// Token Generation
app.UseOAuthAuthorizationServer(OAuthServerOptions);
app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions());

// Cookie Configuration
app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
app.UseTwoFactorSignInCookie(DefaultAuthenticationTypes.TwoFactorCookie, TimeSpan.FromMinutes(5));
app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);
```

I have implemented 2FA in MVC 5 apps before, nothing fancy there. But in Web API + OWIN projects, I think I'm lost. I'd really appreciate it if someone took the time to guide me in the right direction or perhaps provide example code. I need to deploy my 2FA implementation in less than a week.

Thank in advance, fingers crossed, I'll get a helpful response soon. Cheers.

**Comment by CamiloTerevinto** [comment]
@inexuscore That is completely unrelated to this question I had. You should either open a new bug report or question in Stack Overflow (you'll likely get better answers there).

**Comment by inexuscore** [comment]
@CamiloTerevinto I understand that. I couldn't find anything useful on SO, and since you guys were talking about the 2FA bug, I thought I post my question here. I'll open a thread on SO but doubt I'd get any answers there. Bug reports won't help either, the repo is closed and they've moved on to Identity 3 and .NETCore .. any ideas are appreciated.

**Comment by CamiloTerevinto** [comment]
@inexuscore The problem is that here there was no bug. This was my own problem of not knowing how the framework works :) post it there and email me the link, I'll try to check it out

**Comment by inexuscore** [comment]
@CamiloTerevinto most probably, that's what I was thinking. I think I'm missing something. In the config, or the way I'm using the framework. Sure, I'll link you up as soon as I've created the SO thread.
